permit persist :wheel
permit nopass :users as root cmd "/sbin/reboot"
permit nopass :users as root cmd "/sbin/poweroff"
permit nopass :users as root cmd apk args update
permit nopass :users as root cmd apk args upgrade
